    - name: Check var included
      ansible.builtin.assert:
        that:
          - vars_included == 1
          - input_device_id is defined
          - kitty_font is defined
          - kitty_font_size is defined
          - USERNAME is defined
          - NAME is defined
          - EMAIL is defined
          - HOME is defined
          - GROUP is defined
    - name: Check scripts are in correct format
      ansible.builtin.assert:
        that: 
          - true
      loop: "{{ scripts | selectattr('os', 'equalto', os)  | union(scripts | selectattr('os','equalto','both')) }}"
    - name: Check templates are in correct format
      loop: "{{ templates | selectattr('os', 'equalto', os)  | union(templates | selectattr('os','equalto','both')) }}"
      ansible.builtin.assert:
        that: 
          - true
    - name: Check files are in correct format
      loop: "{{ files | selectattr('os', 'equalto', os)  | union(files | selectattr('os','equalto','both')) }}"
      ansible.builtin.assert:
        that: 
          - true


    - name: "Check if {{ USERNAME }} exists"
      when: os == "linux"
      getent:
        database: passwd
        key: "{{ USERNAME }}"


